// Chapter/lesson payload driving the right-side Study Companion panel.

export type AutoStep =
  | { kind: "wait"; ms: number }
  | { kind: "play"; value: boolean }
  | { kind: "theater"; value: "A" | "B" }
  | { kind: "set"; target: "W" | "M" | "WB" | "MB" | "budget"; value: number }
  | { kind: "param"; name: "baseS" | "aW" | "aM" | "nS" | "baseT" | "bS" | "nT" | "cW" | "thrT"; value: number };

export type Lesson = {
  id: number;
  title: string;
  doctrine: string;
  manualOrders: string[];
  interpretation: string;
  auto: AutoStep[];
};

export const WAR_COLLEGE_LESSONS: Lesson[] = [
  {
    id: 1,
    title: "Ch.1–2 • Model ≠ Data (SCM, DAGs, d-sep)",
    doctrine:
      "We don’t read truth off correlations. We fly a structural model (SCM): W,M → S → T → I with optional W→I. Data are generated by the model; identification comes from structure.",
    manualOrders: [
      "Open Structural Equations panel and note S, T, I definitions.",
      "Click ▶️ Play to let Initiative (%) stream. Slide W a little and observe induced co-movement."
    ],
    interpretation:
      "The simulator is a data-generator grounded in a causal graph. Co-movement isn’t proof of causation; structure decides admissible adjustments.",
    auto: [
      { kind: "play", value: true },
      { kind: "wait", ms: 1500 },
      { kind: "play", value: false }
    ]
  },
  {
    id: 2,
    title: "Ch.3 • Back-Door Adjustment (adjust {W,M})",
    doctrine:
      "To estimate S→I, block back-doors into S. Here, {W,M} suffices; that’s why the ATE metric is labelled adj.{W,M}.",
    manualOrders: [
      "Raise aW and aM to make confounding stronger.",
      "Wiggle W quickly while keeping S fixed.",
      "Read ATE(S→I) adj.{W,M} and notice stability despite raw co-movement."
    ],
    interpretation:
      "Back-door says which variables to condition on to reveal the causal effect of S on I. With {W,M} adjusted, confounding is neutralized.",
    auto: [
      { kind: "param", name: "aW", value: 0.7 },
      { kind: "param", name: "aM", value: 0.5 },
      { kind: "play", value: true },
      { kind: "wait", ms: 2000 },
      { kind: "play", value: false }
    ]
  },
  {
    id: 3,
    title: "Ch.4 • Front-Door via Mediation (S→T→I) (needs cW=0)",
    doctrine:
      "When direct confounding can’t be blocked, use a mediating channel you can observe. Here T mediates S→I; front-door becomes valid if W↛I (cW=0).",
    manualOrders: [
      "Set cW to 0 to disable direct W→I.",
      "Lower bS so S barely moves T; see I stagnate.",
      "Raise bS high; now S moves T, and I crosses threshold."
    ],
    interpretation:
      "Front-door exploits the mediator to identify the effect of S on I. The path must be open (good bS), and the direct confounding path must be absent (cW=0).",
    auto: [
      { kind: "param", name: "cW", value: 0 },
      { kind: "param", name: "bS", value: 0.25 },
      { kind: "play", value: true },
      { kind: "wait", ms: 1200 },
      { kind: "param", name: "bS", value: 0.9 },
      { kind: "wait", ms: 1200 },
      { kind: "play", value: false }
    ]
  },
  {
    id: 4,
    title: "Ch.6 • Estimation vs Identification (finite N, noise)",
    doctrine:
      "Identification chooses the valid formula; estimation makes it precise with finite, noisy data.",
    manualOrders: [
      "Increase N (episodes) from ~500 to several thousand.",
      "Add noise via nS and nT; note how the ATE stabilizes with larger N.",
      "Pause/Play to watch variance in Initiative (%)."
    ],
    interpretation:
      "Bigger N reduces variance of estimates but does not change which estimand is valid. Noise inflates variance; structure still rules identification.",
    auto: [
      { kind: "set", target: "budget", value: 0.15 },
      { kind: "param", name: "nS", value: 0.25 },
      { kind: "param", name: "nT", value: 0.2 },
      { kind: "play", value: true },
      { kind: "wait", ms: 1500 },
      { kind: "play", value: false }
    ]
  },
  {
    id: 5,
    title: "Ch.7 • Counterfactuals (PN, PS, PNS) — Decisive Orders",
    doctrine:
      "Counterfactuals answer credit/necessity questions: would the outcome flip if the order were changed?",
    manualOrders: [
      "Make winning hard (raise thrT).",
      "Boost bS (strong S→T).",
      "Read PN, PS, PNS and see which regimes make your order hinge-like."
    ],
    interpretation:
      "High PN: your action is often necessary. High PS: your action is often sufficient. PNS captures hinge power (both).",
    auto: [
      { kind: "param", name: "thrT", value: 0.75 },
      { kind: "param", name: "bS", value: 0.95 },
      { kind: "play", value: true },
      { kind: "wait", ms: 1800 },
      { kind: "play", value: false }
    ]
  },
  {
    id: 6,
    title: "Ch.9 • Transportability (Theater A → Theater B)",
    doctrine:
      "Same structural law; different frontline distributions. Transport uses A’s law with B’s covariate mix.",
    manualOrders: [
      "Set Theater A morale high (M_A≈0.8); Theater B low (M_B≈0.3).",
      "Compare ATE_A, ATE_B, and the transported ATE_A→B.",
      "Increase aM to strengthen morale’s grip on supply; note how the gap shifts."
    ],
    interpretation:
      "Don’t copy tactics naïvely—translate them. Effects depend on both the law and the local mix of conditions.",
    auto: [
      { kind: "theater", value: "A" },
      { kind: "set", target: "M", value: 0.8 },
      { kind: "theater", value: "B" },
      { kind: "set", target: "MB", value: 0.3 },
      { kind: "param", name: "aM", value: 0.45 },
      { kind: "play", value: true },
      { kind: "wait", ms: 1800 },
      { kind: "play", value: false }
    ]
  }
];

